### ISSUE TITLE
Buckets with string values don't work

### ISSUE THREAD

**Issue by erinmiller** [marklogic/node-client-api#100]
Working with the following code:
var db = marklogic.createDatabaseClient(connection);
var q = marklogic.queryBuilder;
var t1 = q.facet('timestamp', q.datatype('xs:dateTime'), q.bucket('2009',  '2009-01-01T00:00:00', '<', '2010-01-01T00:00:00'));
db.documents.query(
q.where(
        q.term('the'))
        .calculate(t1)
        .slice(1,2)
        ).
        stream().

Throws this error:

Users/emiller/dev/node-client-perf/node_modules/marklogic/lib/query-builder.js:2714
    var value1     = (anchor1) ? arguments[1].value[0] : arguments[1];
                                                   ^
TypeError: Cannot read property '0' of undefined
    at Object.bucket (/Users/emiller/dev/node-client-perf/node_modules/marklogic/lib/query-builder.js:2714:52)
    at Object.<anonymous> (/Users/emiller/dev/node-client-perf/new.js:11:60)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by ayuwono** [comment]
Verified and added test case on nodejs-documents-query-facet.js
