### ISSUE TITLE
Document metadata read with stream is failing

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#113]
MarkLogic Build : 20150105

Issue : When we try to read the patch  metadata of a document via stream it is throwing out error that outputStream is not defined. 

Code:
***************************************************************************
it('should read the applied patch on metadata', function(done){
    this.timeout(3000);
    var uri1 = '/test/query/matchList/doc5.json';
    db.documents.read({uris: uri1, categories: ['metadata']}).
    stream().
    on('data', function(data) {
      //console.log(data);
      data.properties.prop2.should.equal('world');
    }).
    on('end', function() {
      done();
    }, done);
  });
  
***************************************************************************
 
Error:
***************************************************************************
<![CDATA[ReferenceError: outputStream is not defined
    at collectStreamBodyObject (/space/builder/builds/linux64/HEAD/qa/node-client-api/lib/mlrest.js:622:7)
    at ConcatStream.&lt;anonymous&gt; (/space/builder/builds/linux64/HEAD/qa/node-client-api/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/space/builder/builds/linux64/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/space/builder/builds/linux64/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /space/builder/builds/linux64/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at process._tickCallback (node.js:419:13)]]>
***************************************************************************

**Comment by ehennum** [comment]
The regression should be gone now.

**Comment by MayankBhatnagar89** [comment]
Issue resolved and the check in test: nodejs-documents-patch-stream.js  also modified as per the output.
