### ISSUE TITLE
Exception is thrown when query returns 0 result

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#12]
Exception:

undefined:0
 
^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tmp/node-client-api/lib/mlrest.js:552:37
    at ConcatStream.<anonymous> (/tmp/node-client-api/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/tmp/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:14)
    at endWritable (/tmp/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:464:3)
    at ConcatStream.Writable.end (/tmp/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:431:5)
    at IncomingMessage.onend (_stream_readable.js:483:10)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)

Sample script:
var exutil = require('./example-util.js');

var marklogic = require('../');
var q = marklogic.queryBuilder;

var db = marklogic.createDatabaseClient(exutil.restReaderConnection);

console.log('Query documents with the Query Builder');

db.query(
  q.where(
    q.collection('/invalid'),
    q.value('name', 'Invalid')
      )
  ).
  // or use result() as in query-by-example.js
  stream().
  on('data', function(document) {
    console.log(document.content.name+' at '+document.uri);
    }).
  on('error', function(error) {
    exutil.failed(error);
    }).
  on('end', function() {
    exutil.succeeded();
    });

**Comment by ayuwono** [comment]
Closing backlog issue, the issue has regression test
