### ISSUE TITLE
'no format for executing resource service' error when invoking resource extension

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#122]
Resource extension implementation (trimmed for clarity): 
```javascript
// ./extensions/resources/query-alert.sjs
function put(context, params, input) {
  // …
};
exports.PUT = resource.put;
```
Installation:
Do I have the correct parameters in `write()`? I've seen examples in the docs with the object wrapper and without.
```javascript
var db = marklogic.createDatabaseClient(conn);
// Gets installed into the Modules database, by default for 8000
db.config.resources.write({
  name: 'alerts',
  format: 'javascript',
  source: fs.createReadStream('./extensions/resources/query-alert.sjs'),
  // everything below this is optional metadata
  title: 'Creates or updates alerts'
}).result(function(response) {
  console.log('Installed extension "%s"', response.name);
}, function(error) {
  console.log(JSON.stringify(error, null, 2));
});
```
Invocation:
```javascript
db.resources.put({
  name: 'alerts', 
  params: { sessionID: sessionID, appID: appID },
  documents: [
    {
      contentType: 'application/json',
      content: { query: 'asdf' } 
    }
  ]
}).result(function(response) {
  console.log(response);
}, function(error) {
  console.log(JSON.stringify(error, null, 2));
});

```

Error:
Also, why is it _possibly_ unhandled?
```
Possibly unhandled Error: no format for executing resource service
    at checkArgs (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/lib/resources-exec.js:39:11)
    at resources.putResourceExec [as put] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/lib/resources-exec.js:150:58)
    at /Users/jmakeig/Workspaces/log-viewer/marklogic-listener.js:106:24
    at tryCatch1 (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/Users/jmakeig/Workspaces/log-viewer/node_modules/marklogic/node_modules/bluebird/js/main/async.js:37:14)
```

Node v0.10.31
Client v1.0.0-e3 from npm
MarkLogic 8.0-20150115
Mac OS X 10.10.1

**Comment by ehennum** [comment]
Are you using the EA3 master branch or the dev branch?  In EA3, executing a resource service required a format.  In the dev branch that's not true.

When the Node.js API detects invalid input before the call returns (such as invalid parameters), it throws an error.  If you don't wrap it in a try/catch, you get an unhandled exception from Node.js itself.

try/catch is a deopt. You might regard it as development-time feedback

**Comment by jmakeig** [comment]
Yup. This was fixed by updating my npm dependency to the latest from the `develop` branch, which, of course won’t be an issue when we ship. For those playing along at home, here's what you need to do in your `package.json` to achieve this:

```json
"dependencies": {
  "marklogic": "marklogic/node-client-api#develop",
}
```

**Comment by ehennum** [comment]
closing because shipped
