### ISSUE TITLE
Consider adding an 'onPossiblyUnhandledRejection' handler to mlrest.js

### ISSUE THREAD

**Issue by dberesford** [marklogic/node-client-api#129]
Currently any unhandled exceptions that get throw in 'pomise' related code do not get caught by an uncaught exception handler, instead a warning is written to stderr as follows:

```
ossibly unhandled Error: die
    at results (/Users/dberesford/work/marklogic/perf2/lib/actions/search.js:90:7)
    at tryCatch1 (/Users/dberesford/work/marklogic/perf2/node_modules/marklogic/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/dberesford/work/marklogic/perf2/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/dberesford/work/marklogic/perf2/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:
```

The correct way to handle these is to use `catch` or `finally`, this is explained in the Bluebird documentation:
https://github.com/petkaantonov/bluebird#error-handling

However, if someone doesn't add a catch to all promises, these errors are swallowed and the code ends up in a limbo kind of state as the promises don't complete.

It would be better (IMO) if these uncaught exceptions bubbled up to the main uncaught exception handler in node. This is achieved by using a 'onPossiblyUnhandledRejection' handler:

```
Promise.onPossiblyUnhandledRejection(function(error){
    throw error;
});
```

**Comment by dberesford** [comment]
Have done the following locally and it works well:

```
diff --git a/lib/mlrest.js b/lib/mlrest.js
index 516ef2b..2be54d7 100644
--- a/lib/mlrest.js
+++ b/lib/mlrest.js
@@ -30,6 +30,10 @@ var mlutil                = require('./mlutil.js');

 var multipartBoundary = 'MLBOUND_' + Date.UTC(2014,12,31);

+Promise.onPossiblyUnhandledRejection(function(error){
+  throw error;
+});
+
 function createAuthenticator(client, user, password, challenge) {
   var authenticator = createAuthInitializer.call(null, user, password)(challenge);
   if (!client.authenticator) {
@@ -116,7 +120,7 @@ function parsePartHeaders(headers) {
   }

   return partHeaders;
-}
+}
```

**Comment by ayuwono** [comment]
Confirmed mlrest.js with the change
