### ISSUE TITLE
geoPath() function fails after upgrade from 1.0.0-ea3 to 1.0.1

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#133]
The following snippet functions in 1.0.0-ea3 but fails under 1.0.1:
```javascript
return db.documents.query(
      qb.where(
          qb.collection('image'),
              qb.geoPath(
                 'location/coordinates',
                  qb.circle(radius, lat, lng)
              )
          ).slice(0,300)
      ).result();
```

the error returned is the following:
```
{ [Error: query documents: response with invalid 400 status]
  message: 'query documents: response with invalid 400 status',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'REST-INVALIDPARAM',
        message: 'REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Could not parse JSON: {"search":{"options":{"search-option":["unfiltered"]}, "query":{"queries":[{"collection-query":{"uri":["image"]}}, {"geo-path":{"path-index":{"text":"location/coordinates", "namespaces":{"circle":{"radius":881, "point":[{"latitude":38.8225909761771, "longitude":-3.33984375}]}}}}}]}}}.XDMP-NONMIXEDCOMPLEXCONT: fn:data(<search:circle xmlns:search="http://marklogic.com/appservices/search"><search:radius>881</search:radius><search:point><search:latitude...</search:circle>) -- Node has complex type with non-mixed complex content' } },
  stack: 'From previous event:\n    at new Promise (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/marklogic/node_modules/bluebird/js/main/promise.js:87:37)\n    at Operation.operationResultPromise (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/marklogic/lib/mlrest.js:1452:17)\n    at Object.callBackMethod [as result] (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/marklogic/lib/mlutil.js:132:17)\n    at search (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/routes.js:128:9)\n    at apisearch (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/routes.js:202:5)\n    at Layer.handle [as handle_request] (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/express/lib/router/route.js:110:13)\n    at Route.dispatch (/Users/tamaspiros/Desktop/workshops/jsconf.asia-workshop-ml/node_modules/express/lib/router/route.js:91:3)' }
```

**Comment by ehennum** [comment]
There's no geospatial query, only a path index reference, and the circle criteria is being passed to the path in the position of a namespace declaration instead of to a geospatial query.

Try something similar to:

      qb.where(
          qb.collection('image'),
          qb.geospatial(
              qb.geoPath(
                  'location/coordinates'
               ),
               qb.circle(10, 20, 30)
              )
          ).slice(0,300)
