### ISSUE TITLE
Running negative word query with only one argument is giving different error message

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#136]
Running this negative query will give different error message

  it('should fail to do word query with one arg', function(done){
    try {
      db.documents.query(
        q.where(
          q.word('Bush')
        ).slice(0)
      ).should.equal('SHOULD HAVE FAILED');
      done();
    }
    catch(error) {
      //console.log(error.toString());
      var strErr = error.toString();
      strErr.should.equal('Error: subquery must supply literal criteria for: Bush');
      done();
    }
  });

Actual result: 'Error: subquery is not a query definition: [object Object]'

Expected result: 'Error: subquery must supply literal criteria for: Bush'

<testcase classname="Document query negative test" name="should fail to do word query with one arg" time="0.001" message="expected 'Error: subquery is not a query definition: [object Object]' to be 'E
rror: subquery must supply literal criteria for: Bush'"><failure classname="Document query negative test" name="should fail to do word query with one arg" time="0.001" message="expected 'Error: subque
ry is not a query definition: [object Object]' to be 'Error: subquery must supply literal criteria for: Bush'"><![CDATA[AssertionError: expected 'Error: subquery is not a query definition: [object Obj
ect]' to be 'Error: subquery must supply literal criteria for: Bush'
    at Assertion.fail (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/should/lib/assertion.js:228:17)
    at Assertion.prop.(anonymous function) (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/should/lib/assertion.js:69:14)
    at Context.&lt;anonymous&gt; (/space/SVN_HOME/HEAD/qa/node-client-api/test-complete/nodejs-documents-query-negative.js:171:21)
    at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
    at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
    at /usr/lib/node_modules/mocha/lib/runner.js:452:12
    at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
    at /usr/lib/node_modules/mocha/lib/runner.js:309:7
    at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
    at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:330:15)]]></failure></testcase>

**Comment by ehennum** [comment]
The old error message should appear again (moved type checking after constraint checking) and, in general type-checking error messages should be better.

**Comment by ayuwono** [comment]
The old error message appears again and test is passed
