### ISSUE TITLE
Deprecating warning and unit-test failures after upgrading node to 0.12.0

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#144]
After upgrading node to stable version 0.12.0, and running the unit-test (test-basic), we found a warning and a couple of failures

Deprecation warning:
child_process: customFds option is deprecated, use stdio instead.

Error on unescaped characters:
  1) document negative should fail to write a document with a non-existent transaction:
     TypeError: Request path contains unescaped characters.
      at new ClientRequest (_http_client.js:73:11)
      at MarkLogicClient.exports.request (http.js:49:10)
      at authenticatedRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:324:34)
      at Object.startRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:267:5)
      at documents.writeContent (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:774:17)
      at documents.writeDocumentsImpl (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:597:27)
      at documents.writeDocuments [as write] (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:558:29)
      at Context.<anonymous> (/space/SVN_HOME/HEAD/qa/node-client-api/test-basic/documents-negative.js:103:18)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

  2) document negative should fail to delete a document with a non-existent transaction:
     TypeError: Request path contains unescaped characters.
      at new ClientRequest (_http_client.js:73:11)
      at MarkLogicClient.exports.request (http.js:49:10)
      at authenticatedRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:324:34)
      at Object.startRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:267:5)
      at documents.removeDocumentImpl (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:1126:17)
      at documents.removeDocument [as remove] (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:1065:29)
      at Context.<anonymous> (/space/SVN_HOME/HEAD/qa/node-client-api/test-basic/documents-negative.js:136:18)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by ehennum** [comment]
I didn't notice the deprecation warning ("child_process: customFds option is deprecated, use stdio instead") -- how can I reproduce that?

**Comment by ayuwono** [comment]
Investigating the deprecation warning

**Comment by ayuwono** [comment]
Hi Erik, we are running mocha on the test. We also reported that the warning shows up on windows platform. I changed the node engine version on package.json to 0.12.0.

**Comment by ehennum** [comment]
Are you still seeing the unit test errors?  Or is it just the deprecation message?  

If the deprecation message, do you see it on install or on every mocha test run?  

If on every mocha run, do you see it running the basic unit tests or the complete regression test or both?

**Comment by ayuwono** [comment]
No unit-test error, it's just a deprecation message

We see the deprecation message on every mocha test run on both test-basic and test-complete. It also happen when you run individual test on both test-basic and test-complete

Here is the package.json that we have:

{
  "author": "MarkLogic",
  "name": "marklogic",
  "description": "The official MarkLogic Node.js client API.",
  "homepage": "http://github.com/marklogic/node-client-api",
  "version": "1.0.1",
  "license": "Apache-2.0",
  "main": "./lib/marklogic.js",
  "keywords": [
    "marklogic",
    "nosql",
    "database",
    "dbms",
    "search",
    "query",
    "json",
    "xml",
    "http",
    "xquery",
    "xpath"
  ],
  "dependencies": {
    "bluebird": "^2.9.6",
    "concat-stream": "^1.4.7",
    "core-util-is": "^1.0.1",
    "deepcopy": "^0.4.0",
    "dicer": "^0.2.3",
    "multipart-stream": "^1.0.0",
    "qs": "^2.3.3",
    "through2": "^0.6.3",
    "www-authenticate": "^0.6.2",
    "yakaa": "^1.0.1"
  },
  "repository": {
    "type": "git",
    "url": "http://github.com/marklogic/node-client-api.git"
  },
  "engines": {
    "node": "0.12.0"
  },
  "devDependencies": {
    "bunyan": "^1.3.3",
    "gulp": "^3.8.10",
    "gulp-jsdoc": "^0.1.4",
    "gulp-jshint": "^1.9.2",
    "gulp-mocha": "^2.0.0",
    "jsdoc": "^3.3.0-beta1",
    "jshint": "^2.6.0",
    "mocha": "^2.1.0",
    "read": "^1.0.5",
    "should": "^4.6.5",
    "winston": "^0.9.0"
  }
}

**Comment by ehennum** [comment]
Strange.  I don't see any deprecation messages when I run Mocha against 0.12.0

Just to confirm, does you PATH point at the 0.12.0 instance?  Did you install Mocha with npm -g on 0.12.0 and use that instance of Mocha?

Also, given the way the community is going, testing on io.js is becoming as or more important than testing on Node 0.12.0

**Comment by ehennum** [comment]
Sending back with the questions above ...

**Comment by ayuwono** [comment]
It turns out that this is mocha deprecation warning, not because of node engine. Closing this issue
