### ISSUE TITLE
Unable to read document with transform in which its params value has a space in it

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#149]
Steps:
======
1) Install this javascript transform:
function paramTransform(context, params, document) {
  var newDoc = document.toObject();
  var newTitle = params.title;
  newDoc.title = newTitle;
  return newDoc;
}

module.exports = {
  transform: paramTransform
};

2) Write some documents to DB

3) Read the uris back with the transform with params. The param value has a space in it

  it('should return transformed content and metadata during read', function(done){
    db.documents.read({
      uris: [uri1, uri2],
      categories: ['content', 'metadata'],
      transform: [transformName, {title: 'new title'}]
    }).
    result(function(response) {
...

It returns an error that says: "Request path contains unescaped characters."

<testcase classname="Transform with params" name="should return transformed content and metadata during read" time="0.002" message="Request path contains unescaped characters."><failure classname="Tra
nsform with params" name="should return transformed content and metadata during read" time="0.002" message="Request path contains unescaped characters."><![CDATA[TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at MarkLogicClient.exports.request (http.js:49:10)
    at challengeRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:295:35)
    at Object.startRequest (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:265:5)
    at documents.readDocumentsImpl (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:406:17)
    at documents.readDocuments [as read] (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:265:28)
    at Context.&lt;anonymous&gt; (/space/SVN_HOME/HEAD/qa/node-client-api/test-complete/nodejs-transform-params.js:64:18)
    at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
    at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
    at /usr/lib/node_modules/mocha/lib/runner.js:452:12
    at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
    at /usr/lib/node_modules/mocha/lib/runner.js:309:7
    at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
    at Immediate._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:358:17)]]></failure></testcase>

**Comment by ehennum** [comment]
test should work now

**Comment by ayuwono** [comment]
Test is run again and passed
