### ISSUE TITLE
Reading non-existent document metadata is throwing an error now, it returns an empty array before

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#157]
Reading non-existent document metadata is throwing an error now, it returns an empty array before

  it('should fail to read metadata from non-existent document', function(done){
    db.documents.read({
      uris: '/doc/nonExistent.json',
      categories: ['metadata']
      }).
    result(function(response) {
      response.length.should.equal(0);
      done();
    }, function(error) {
      //console.log(error);
      done();
      });
  });

Result:
<testcase classname="Document CRUD negative test" name="should fail to read metadata from non-existent document" time="0" message="Cannot read property 'collections' of null"><failure classname="Docum
ent CRUD negative test" name="should fail to read metadata from non-existent document" time="0" message="Cannot read property 'collections' of null"><![CDATA[TypeError: Cannot read property 'collectio
ns' of null
    at collectMetadata (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:1053:45)
    at Operation.singleReadOutputTransform [as outputTransform] (/space/SVN_HOME/HEAD/qa/node-client-api/lib/documents.js:219:28)
    at Operation.collectBodyObject (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:1350:36)
    at collectPromiseBodyObject (/space/SVN_HOME/HEAD/qa/node-client-api/lib/mlrest.js:590:32)
    at ConcatStream.&lt;anonymous&gt; (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at afterWrite (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
    at /space/SVN_HOME/HEAD/qa/node-client-api/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
    at process._tickCallback (node.js:355:11)]]></failure></testcase>

**Comment by ehennum** [comment]
In my testing, this bug was reproducible before the correct fix for #153 but not after the correct fix.  In other words, I believe the fix for #153 also fixed this issue.

**Comment by ayuwono** [comment]
Verified passed after the fix
