### ISSUE TITLE
Value Query changes between v1.0.1 and v1.0.2

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#171]
I have an application that uses ValueQueries and it works fine against the Node.js client API v1.0.1. After an upgrade to v1.0.2 I get the following error:

subquery is not a query definition: Array [{"value-query":{"json-property":"homeworld","text":["Corellia"]}}]
    at checkQuery (/Users/tamaspiros/Desktop/mlu-sw/node_modules/marklogic/lib/query-builder.js:133:11)
    at Object.where (/Users/tamaspiros/Desktop/mlu-sw/node_modules/marklogic/lib/query-builder.js:3342:22)
    at selectAll (/Users/tamaspiros/Desktop/mlu-sw/routes.js:53:10)
    at apiindex (/Users/tamaspiros/Desktop/mlu-sw/routes.js:133:3)
    at Layer.handle [as handle_request] (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/layer.js:82:5)
    at /Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:166:3)
    at router (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:35:12)
    at Layer.handle [as handle_request] (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:302:13)
    at /Users/tamaspiros/Desktop/mlu-sw/node_modules/express/lib/router/index.js:270:7

I can provide you with more information I'm just not sure what is required.

**Comment by ehennum** [comment]
It would be helpful to see the source code for the query.

**Comment by tamaspiros** [comment]
Sure.
(few things to note:
* Element Range Indexes are in place
* assume we have var _ = require('lodash');

```javascript
var selectAll = function selectAll(facets) {
  if (Object.keys(facets).length === 0) {
    return db.documents.query(
      qb.where(
        qb.collection('character')
      )
      .calculate(
        qb.facet('homeworld'),
        qb.facet('species'),
        qb.facet('alliance')
      )
      .slice(1, 100)
    ).result();
  } else {
    var valueQuery = [];
    _.each(facets[0], function(value, category) {
      valueQuery.push(qb.value(category, value));
    });
    return db.documents.query(
      qb.where(
        qb.collection('character'), valueQuery
        )
        .calculate(
          qb.facet('homeworld'),
          qb.facet('species'),
          qb.facet('alliance')
        )
        .slice(1, 100)
      ).result();
  }
};
```

And the usage:

```javascript
var facetsHandler = function facetsHandler(queryOptions) {
  var acceptableFacets = ['alliance', 'homeworld', 'species'];
  var facetHandler = [];
  var tmp          = {};
  _.each(queryOptions, function(value, key) {
    if (_.contains((acceptableFacets), key)) {
      tmp[key] = value;
      facetHandler.push(tmp);
    }
  });

  return facetHandler;
}

var apicharacters = function apiindex(req, res) {
  var data = {};
  data.results = [];
  data.facets = [];
  var facets = req.query ? facetsHandler(req.query) : '';
  var counter = 0;
  selectAll(facets).then(function(documents) {
    if (documents[0].total !== 0) {
      data.facets = documents[0].facets;
      documents.forEach(function(document) {
        if (typeof document.uri !== 'undefined') {
          getImage(document.content)
          .then(function(documentData) {
            counter++;
            data.results.push(documentData);
            if (counter === documents.length - 1) {
              res.json(data);
            }
          });
        }
      });
    } else {
      res.json('No documents');
    }
  });
};
```

I guess I could come up with an easier to understand example. However let me know if you see something that is obviously wrong here...

**Comment by tamaspiros** [comment]
Here's a simplified example:

```javascript
var marklogic  = require('marklogic');
var connection = require('./../settings').connection;
var db         = marklogic.createDatabaseClient(connection);
var qb         = marklogic.queryBuilder;
var _          = require('lodash');

var facetsHandler = function facetsHandler(queryOptions) {
  var acceptableFacets = ['alliance', 'homeworld', 'species'];
  var facetHandler = [];
  var tmp          = {};
  _.each(queryOptions, function(value, key) {
    if (_.contains((acceptableFacets), key)) {
      tmp[key] = value;
      facetHandler.push(tmp);
    }
  });

  return facetHandler;
}

var facets = [ { homeworld: 'Alderaan' } ];

function selectAll(facets) {
  var valueQuery = [];
  _.each(facets[0], function(value, category) {
   valueQuery.push(qb.value(category, value));
 });
 console.log(valueQuery);
 return db.documents.query(
   qb.where(
     qb.collection('character'), valueQuery
     )
     .calculate(
       qb.facet('homeworld'),
       qb.facet('species'),
       qb.facet('alliance')
     )
     .slice(1, 100)
   ).result();

}

selectAll(facets).then(function(data) {
  console.log(data);
});
```

Error: 
```
[ { 'value-query': { 'json-property': 'homeworld', text: [Object] } } ]
/Users/tamaspiros/Desktop/workshops/mlu-sw/node_modules/marklogic/lib/query-builder.js:133
    throw new Error('subquery is not a query definition: '+mlutil.identify(que
          ^
Error: subquery is not a query definition: Array [{"value-query":{"json-property":"homeworld","text":["Alderaan"]}}]
    at checkQuery (/Users/tamaspiros/Desktop/workshops/mlu-sw/node_modules/marklogic/lib/query-builder.js:133:11)
    at Object.where (/Users/tamaspiros/Desktop/workshops/mlu-sw/node_modules/marklogic/lib/query-builder.js:3342:22)
    at selectAll (/Users/tamaspiros/Desktop/workshops/mlu-sw/test/app.js:30:7)
    at Object.<anonymous> (/Users/tamaspiros/Desktop/workshops/mlu-sw/test/app.js:43:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by ehennum** [comment]
Thanks for the source.

The query builder improved validation in 1.0.2.

You can't mix arrays of queries and individual query arguments.  However, something similar to the following should work:

    var queries = [qb.collection('character')];
    _.each(facets[0], function(value, category) {
      queries.push(qb.value(category, value));
    });
    return db.documents.query(
      qb.where(queries)

**Comment by tamaspiros** [comment]
the suggested fix works - high five @ehennum :+1: :smile:
