### ISSUE TITLE
Patching with null fails

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#232]
Here's the test:
```javascript
var should = require('should');

var testconfig = require('../etc/test-config-qa.js');

var marklogic = require('../');
var q = marklogic.queryBuilder;
var p = marklogic.patchBuilder;

var db = marklogic.createDatabaseClient(testconfig.restReaderConnection);
var dbWriter = marklogic.createDatabaseClient(testconfig.restWriterConnection);
var dbAdmin = marklogic.createDatabaseClient(testconfig.restAdminConnection);

describe('null patch test', function(){
  before(function(done){
    this.timeout(10000);
    dbWriter.documents.write({
      uri: '/doc1.json',
      contentType: 'application/json',
      content: {
        title: 'Vannevar Bush',
        popularity: 5,
        id: '0011',
        date: '2005-01-01',
        price: {
             amt: 0.1
           },
        p: 'Vannevar Bush wrote an article for The Atlantic Monthly'
        }
      }).
    result(function(response){done();}, done);
  });

  it('should apply patch...works fine', function(done){
    dbWriter.documents.patch('/doc1.json',
      p.replace("/popularity", 111)
    ).result(function(response) {
        console.log(response);
        done();
    }, function(error){
		console.log(error)
    	done()
    });
  });
  
  it('should apply patch but fails...this is a bug', function(done){
    dbWriter.documents.patch('/doc1.json',
      p.replace("/popularity", null)
    ).result(function(response) {
        console.log(response);
        done();
    }, function(error){
		console.log(error)
    	done()
    });
  });

  it('should remove the documents', function(done){
    dbAdmin.documents.removeAll({
      all: true
    }).
    result(function(response) {
      response.should.be.ok;
      done();
    }, done);
  });
  
});
```

Error:
```
 TypeError: Cannot read property 'apply' of null
      at Object.replace (lib/patch-builder.js:416:18)
      at Context.<anonymous> (test-complete/null-patch-bug.js:64:9)
```

**Comment by ehennum** [comment]
Might be an issue at both the REST API and Node.js API layers

**Comment by ayuwono** [comment]
Shipped https://bugtrack.marklogic.com/bug/37787
