### ISSUE TITLE
Running near query will throw subquery is not a query definition error

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#316]
Running near query will throw subquery is not a query definition error

```
    db.documents.query(
      q.where(
        q.near(
          q.term('Bush'),
          q.term('Atlantic'),
          6,
          q.weight(1)
        )
      ))
```

Error:

```
Error: subquery is not a query definition: object {"near-query":{"distance":6,"distance-weight":1,"queries":[{"term-query":{"text":["Bush"]}},{"term-query":{"text":["Atlantic"]}}]}}
      at checkQuery (/space/builds/linux64/HEAD/qa/node-client-api/lib/query-builder.js:137:13)
      at Object.where (/space/builds/linux64/HEAD/qa/node-client-api/lib/query-builder.js:3515:20)
      at Context.<anonymous> (nodejs-documents-query.js:282:9)
```

Data:

```
dbWriter.documents.write({
      uri: '/test/query/matchDir/doc1.json',
      collections: ['matchCollection1'],
      contentType: 'application/json',
      content: {
        title: 'Vannevar Bush',
        popularity: 5,
        id: '0011',
        date: '2005-01-01',
        price: {
             amt: 0.1
           },
        p: 'Vannevar Bush wrote an article for The Atlantic Monthly'
        }
      }, {
      uri: '/test/query/matchDir/doc2.json',
      collections: ['matchCollection1', 'matchCollection2'],
      contentType: 'application/json',
      content: {
        title: 'The Bush article',
        popularity: 4,
        id: '0012',
        date: '2006-02-02',
        price: {
             amt: 0.12
           },
        p: 'The Bush article described a device called a Memex'
        }
      }, {
      uri: '/test/query/matchDir/doc3.json',
      collections: ['matchCollection2'],
      contentType: 'application/json',
      content: {
        title: 'For 1945',
        popularity: 3,
        id: '0013',
        date: '2007-03-03',
        price: {
             amt: 1.23
           },
        p: 'For 1945, the thoughts expressed in the Atlantic Monthly were groundbreaking'
        }
      }, {
      uri: '/test/query/matchDir/doc4.json',
      collections: [],
      contentType: 'application/json',
      content: {
        title: 'Vannevar served',
        popularity: 5,
        id: '0024',
        date: '2008-04-04',
        price: {
             amt: 12.34
           },
        p: 'Vannevar served as a prominent policymaker and public intellectual'
        }
      }, {
        uri: '/test/query/matchList/doc5.json',
        collections: ['matchList'],
        contentType: 'application/json',
        content: {
          title: 'The memex',
          popularity: 5,
          id: '0026',
          date: '2009-05-05',
          price: {
               amt: 123.45
             },
          p: 'The Memex, unfortunately, had no automated search feature policy'
          }
        })
```

**Comment by ayuwono** [comment]
Verified passed on regression 11/11
