### ISSUE TITLE
Socket connection error across Node.js tests, error on Unexpected end of multipart data

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#414]
This is a regression bug, starting on build ML-9 07/25, we have socket connection error on Node.js. Here is one example

Write these documents to DB:
```
var docuri = '/foo/bar/test1.json';
  var docuri2 = '/foo/bar/test2.json';

  before(function(done) {
    this.timeout(10000);
    db.documents.write({
      uri: docuri,
      collections: ['coll0', 'coll1'],
      contentType: 'application/json',
      quality: 10,
      permissions: [
        {'role-name':'app-user', capabilities:['read', 'node-update']},
        {'role-name':'app-builder', capabilities:['read', 'update']}
      ],
      properties: {prop1:'foo', prop2:25},
      content: {id:12, name:'Jason'}
    }, {
      uri: docuri2,
      collections: ['coll0', 'coll1'],
      contentType: 'application/json',
      quality: 10,
      permissions: [
        {'role-name':'app-user', capabilities:['read', 'node-update']},
        {'role-name':'app-builder', capabilities:['read', 'update']}
      ],
      properties: {prop1:'bar', prop2:33},
      content: {id:245, name:'Paul'}
    }).result(function(response){done();}, done);
  });
```
Then try to read the documents:
```
db.documents.read({uris: [docuri, docuri2], categories:['content']})
```

It will produce this error:
```
     Error: Parse Error
      at Error (native)
      at Socket.socketOnData (_http_client.js:361:20)
      at readableAddChunk (_stream_readable.js:177:18)
      at Socket.Readable.push (_stream_readable.js:135:10)
      at TCP.onread (net.js:542:20)
```

Complete error trace:
```
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  bytesParsed: 643,
  code: 'HPE_INVALID_CONSTANT',
  otherErrors:
   [ Error: Unexpected end of multipart data
         at /space/builds/linux64/b9_0/qa/node-client-api/node_modules/dicer/lib/Dicer.js:62:28
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9) ] }
```

To run the test:
1) git clone https://github.com/marklogic/node-client-api node-client-api
2) cd node-client-api
3) git checkout develop
4) npm install --no-optional
5) node etc/test-setup-qa.js
6) ./node_modules/mocha/bin/mocha --timeout 30000 test-complete/nodejs-documents-crud.js

**Comment by ayuwono** [comment]
Same error when doing documents query, it has something to do with "Unexpected end of multipart data"

```
db.documents.query(
      q.where(
        q.word('title', 'bush')
      )).
```

```
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  bytesParsed: 1022,
  code: 'HPE_INVALID_CONSTANT',
  otherErrors:
   [ Error: Unexpected end of multipart data
         at /space/builds/linux64/b9_0/qa/node-client-api/node_modules/dicer/lib/Dicer.js:62:28
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by ayuwono** [comment]
The pattern so far is happening on read, query, parse, extract (more on documents GET request)

**Comment by ayuwono** [comment]
The core issue seems to be on https://bugtrack.marklogic.com/46893

**Comment by wooldridge** [comment]
Thanks for digging into this and matching it to the Bugtrack issue.

**Comment by ayuwono** [comment]
Bug 46893 is fixed and passed on 07/31 regression
