### ISSUE TITLE
Unable to use column accessor as a variable on plan

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#454]
This test is running fine on Optic SJS, but it's failing on Node.js

Build: 9.0 nightly

Setup:
1) git checkout develop
2) Run the setup: node config-optic/setupqa.js
3) When you run this test script:
```
  it('TEST 11 - inner join with accessor plan and on', function(done){
    const plan1 =
      op.fromView('opticFunctionalTest', 'detail', 'myDetail');
    const plan2 =
      op.fromView('opticFunctionalTest', 'master', 'myMaster');
    const masterIdCol1 = plan1.col('masterId');
    const masterIdCol2 = plan2.col('id');
    const detailIdCol = plan1.col('id');
    const detailNameCol = plan1.col('name');
    const masterNameCol = plan2.col('name');
    const output =
      plan1.joinInner(plan2, op.on(masterIdCol1, masterIdCol2), op.ge(detailIdCol, 3))
      .select([masterIdCol2, masterNameCol, detailIdCol, detailNameCol])
      .orderBy(op.desc(detailNameCol))
      .offsetLimit(1, 100)
    db.rows.query(output, { format: 'json', structure: 'object', columnTypes: 'header' })
    .then(function(output) {
      console.log(JSON.stringify(output, null, 2));
      done();
    }, function(error) {console.log(error); done(); });
  });

```
It will fail with this error:
```
{ Error: query rows: response with invalid 500 status
    at Operation.makeError (/space/builds/linux64/b9_0/qa/node-client-api/lib/operation.js:221:10)
    at Operation.isResponseStatusOkay (/space/builds/linux64/b9_0/qa/node-client-api/lib/responder.js:971:33)
    at Operation.responseDispatcher (/space/builds/linux64/b9_0/qa/node-client-api/lib/responder.js:49:29)
    at ClientRequest.callBackMethod (/space/builds/linux64/b9_0/qa/node-client-api/lib/mlutil.js:123:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  message: 'query rows: response with invalid 500 status',
  statusCode: 500,
  body:
   { errorResponse:
      { statusCode: 500,
        status: 'Internal Server Error',
        messageCode: 'INTERNAL ERROR',
        message: 'SQL-AMBCOLUMN: return plan.execute(query); -- Ambiguous column reference: found myMaster.id and myDetail.id . See the MarkLogic server error log for further detail.' } } }

```

It seems that Node.js Optic layer can't distinguish the column reference with the qualifier on plan accessor. It has the same column name (id), but with different qualifier (myMaster and myDetail)

On SJS, the same query works fine. Run it on qconsole, against nodeOpticFunctionalTest DB:
```
'use strict';

const op = require('/MarkLogic/optic');
const plan1 =
      op.fromView('opticFunctionalTest', 'detail', 'myDetail');
    const plan2 =
      op.fromView('opticFunctionalTest', 'master', 'myMaster');
    const masterIdCol1 = plan1.col('masterId');
    const masterIdCol2 = plan2.col('id');
    const detailIdCol = plan1.col('id');
    const detailNameCol = plan1.col('name');
    const masterNameCol = plan2.col('name');
    const output =
      plan1.joinInner(plan2, op.on(masterIdCol1, masterIdCol2), op.ge(detailIdCol, 3))
      .select([masterIdCol2, masterNameCol, detailIdCol, detailNameCol])
      .orderBy(op.desc(detailNameCol))
      .offsetLimit(1, 100)
      .result();
      output;
```
Result:
```
{"myMaster.id":1, "myMaster.name":"Master 1", "myDetail.id":5, "myDetail.name":"Detail 5"}
{"myMaster.id":2, "myMaster.name":"Master 2", "myDetail.id":4, "myDetail.name":"Detail 4"}
{"myMaster.id":1, "myMaster.name":"Master 1", "myDetail.id":3, "myDetail.name":"Detail 3"}
```

**Comment by ayuwono** [comment]
I think it's not about the qualifier, it's about the column accessor variables

    const masterIdCol1 = plan1.col('masterId');
    const masterIdCol2 = plan2.col('id');
    const detailIdCol = plan1.col('id');
    const detailNameCol = plan1.col('name');
    const masterNameCol = plan2.col('name');

If I replace the variables with this, it will work
 plan1.joinInner(plan2, op.on(op.viewCol('myDetail', 'masterId'), op.viewCol('myMaster', 'id')), op.ge(op.viewCol('myDetail', 'id'), 3))

**Comment by ehennum** [comment]
Fixed implementation - the unit tests were not checking the right thing.

**Comment by ayuwono** [comment]
Added test on views
