### ISSUE TITLE
xmlElement() can't take function as a content

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#462]
Steps:
1) Setup: node config-optic/setupqa.js
2) This script will fail:
```
    const bb = op.prefixer('http://marklogic.com/baseball/players/');
    const ageCol = op.col('age');
    const idCol = op.col('id');
    const nameCol = op.col('name');
    const posCol = op.col('position');
    const output =
      op.fromTriples([
        op.pattern(idCol, bb('age'), ageCol),
        op.pattern(idCol, bb('name'), nameCol),
        op.pattern(idCol, bb('position'), posCol)
      ])
      .where(
        op.and(
          op.le(ageCol, 25),
          op.eq(posCol, 'Catcher')
        )
      )
      .orderBy(op.desc(ageCol))
      .select([
        op.as('PlayerName', nameCol),
        op.as('PlayerPosition', posCol),
        op.as('PlayerAge', ageCol)
      ])
      .select([
        'PlayerName',
        'PlayerPosition',
        'PlayerAge',
        op.as('xml',
          op.xmlDocument(
            op.xmlElement(
              'root',
              op.xmlAttribute('attrA', op.col('PlayerName')),
              [
                op.xmlElement('elemA', null, op.col('PlayerPosition')),
                op.xmlElement('elemACodePoints', null, op.fn.stringToCodepoints(op.col('PlayerPosition'))),
                op.xmlElement('elemB', null, op.col('PlayerAge')),
                op.xmlElement('elemC', null, op.math.sqrt(op.col('PlayerAge')))
              ]
            )
          )
        )
      ])
    db.rows.query(output, { format: 'xml', structure: 'object', columnTypes: 'rows' })
    .then(function(output) {
```

It's on xmlElement that has function as a content

op.xmlElement('elemACodePoints', null, op.fn.stringToCodepoints(op.col('PlayerPosition')))
op.xmlElement('elemC', null, op.math.sqrt(op.col('PlayerAge')))

Error:
```
Error: content argument at 2 of PlanBuilder.xmlElement() must have type XmlContentNode or PlanColumn or PlanParam
      at castArg (/space/builds/linux64/b9_0/qa/node-client-api/lib/plan-builder-base.js:73:13)
      at checkArg (/space/builds/linux64/b9_0/qa/node-client-api/lib/plan-builder-base.js:60:15)
      at args.map (/space/builds/linux64/b9_0/qa/node-client-api/lib/plan-builder-base.js:258:12)
      at Array.map (native)
      at Object.makePositionalArgs (/space/builds/linux64/b9_0/qa/node-client-api/lib/plan-builder-base.js:255:15)
      at Builder.xmlElement (/space/builds/linux64/b9_0/qa/node-client-api/lib/plan-builder-generated.js:7033:18)
      at Context.<anonymous> (nodejs-optic-nodes.js:195:19)
```
This is working fine on Optic API SJS

**Comment by ehennum** [comment]
Expressions and literals should now be allowed as text content in XML elements or as values for JSON array items or JSON object properties.  The plan-node.js basic test has the specifics.

**Comment by ayuwono** [comment]
Verified passed and added test on nodes constructor
