### ISSUE TITLE
Date value test failures with Node.js version 8.9.1

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#475]
Upgrading to Node.js version 8.9.1 and running test-basic on the develop branch yields the following two failures (these failures do not occur with Node.js version 6.9.0):
```
805 passing (1m)
  2 failing

  1) server-side call
       to eval JavaScript
         should generate a date value:

      AssertionError: expected 2010-10-08 10:17:15.125 -0700 to equal 2010-10-08 03:17:15.125 -0700
      + expected - actual

      -[Date: 2010-10-08T17:17:15.125Z]
      +[Date: 2010-10-08T10:17:15.125Z]
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at test-basic/server-exec.js:109:32
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2) server-side call
       to invoke JavaScript
         should return a date value:

      AssertionError: expected 2010-10-08 10:17:15.125 -0700 to equal 2010-10-08 03:17:15.125 -0700
      + expected - actual

      -[Date: 2010-10-08T17:17:15.125Z]
      +[Date: 2010-10-08T10:17:15.125Z]
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at test-basic/server-exec.js:343:32
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by ehennum** [comment]
Maybe a time zone issue of some kind -- given that both are 7 hours off.

**Comment by wooldridge** [comment]
These failures are due to a change in how dates are handled in Node.js in version 8 (on account of the underlying ES2015 spec). See here for details:

https://github.com/nodejs/node/issues/13210

When the following is eval'ed via the Node.js Client API:

`new Date("2010-10-08T10:17:15.125Z)`

the MarkLogic server returns a date without a time zone:

`2010-10-08T10:17:15.125`

The [ES2015 spec](https://tc39.github.io/ecma262/#sec-date-time-string-format) says:

 > When the time zone offset is absent, date-only forms are interpreted as a UTC time and *date-time forms are interpreted as a local time*.

Thus the following line in the API code:

https://github.com/marklogic/node-client-api/blob/master/lib/server-exec.js#L85

yields the following value, which is shifted based on the local time zone:

`2010-10-08T17:17:15.125Z`

This new behavior breaks the two tests, which compare that value with the following that uses a value (with a timezone):

`new Date('2010-10-08T10:17:15.125Z')`

A fix is to eval and test against the following, which avoids the time zone-related mismatch:

`2010-10-08T10:17:15.125`

**Comment by ehennum** [comment]
Good sleuthing.

**Comment by wooldridge** [comment]
@ayuwono, FYI, in looking ahead to supporting Node.js versions 8 and beyond, you may have to adjust tests that eval dates on the server (and possibly other date tests).

**Comment by wooldridge** [comment]
Merged after passing test-basic locally and on Jenkins.
