### ISSUE TITLE
bad XPath in patch select causes ReferenceError

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#48]
The attached program contains a patch with an invalid XPath expr in the select (there is a "/" where there shouldn't be). In the raw, the patch looks like this:
```json
{ "patch": [
  {"replace-insert":{
    "select":"node()/[. = 'c4bv2']",
    "context":"/theTop/node('child4b')",
    "position":"last-child",
    "content":"REPLACED4"}}
]}
```
It causes the server to cough up a RESTAPI-INVALIDCONTENT error when you force feed it directly to the REST layer. Not the most helpful of errors, but OK. Feed the same bad select in through node client and you get the collapse of civilization as we know it, which does not strike me as a measured response to one little "/":
```
F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:975
  if (!valcheck.isNullOrUndefined(input.body)) {
                                  ^
ReferenceError: input is not defined
    at Operation.logError (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:975:35)
    at rejectedPromise (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:1054:17)
    at Operation.dispatchEnd (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:1010:7)
    at Operation.dispatchEndError (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:946:13)
    at F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:608:23
    at ConcatStream.<anonymous> (F:\javascript\my-project\node_modules\marklogic\node_modules\concat-stream\index.js:32:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (F:\javascript\my-project\node_modules\marklogic\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:460:14)
    at afterWrite (F:\javascript\my-project\node_modules\marklogic\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:340:3)
    at F:\javascript\my-project\node_modules\marklogic\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:327:9
```

Reproducible test case:
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');
var db = marklogic.createDatabaseClient(my.connInfo);

// (1) Insert the base document into the database
db.documents.write({
  uri: '/patch/replace-insert.json',
  contentType: 'application/json',
  content: {
    theTop: {
      child1: { grandchild: 'gcv' },
      child2: 'c2v',
      child3a: [ 'c3av1', 'c3av2' ],
      child3b: [ 'c3bv1', 'c3bv2' ],
      child4a: [ 'c4av1', 'c4av2' ],
      child4b: [ 'c4bv1', 'c4bv2' ],
      child5: [ { c5a: 'c5v1' }, { c5b: 'c5v2' } ]
  } }
}).result(function(response) {
  // (2) Patch the document
  var pb = marklogic.patchBuilder;
  db.documents.patch(response.documents[0].uri,
    pb.replaceInsert('node()/[. = "c4bv2"]',
              '/theTop/node("child4b")', 'last-child',
              'REPLACED4')
  );
});
```

The my-connection.js module looks like this:
```javascript
module.exports = {
  connInfo: {
    host: ...,
    port: ...,
    user: ...,
    password: ...
  }
};
```

**Comment by ayuwono** [comment]
Closing backlog issue, the issue has regression test
