### ISSUE TITLE
node-client-api fails with a complaint about Bluebird

### ISSUE THREAD

**Issue by rhedin** [marklogic/node-client-api#504]
Hi.  I cloned and built node-client-api, then I ran examples/setup.js according to the instructions.  It fails.  I tried master and 2.0-master with the same result.  Is this a bug in the software?

```Ricks-MBP:node-client-api rickhedin$ git status
On branch 2.0-master
Your branch is up-to-date with 'origin/2.0-master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   npm-shrinkwrap.json

no changes added to commit (use "git add" and/or "git commit -a")
Ricks-MBP:node-client-api rickhedin$ node examples/setup.js 
admin user (default=admin): rickhedin
admin password: ***********

checking for REST users

/Users/rickhedin/work/180808/node-client-api/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
Error: POST /manage/v2/roles: cannot process response with 400 status
    at Operation.makeError (/Users/rickhedin/work/180808/node-client-api/lib/operation.js:215:10)
    at Operation.isResponseStatusOkay (/Users/rickhedin/work/180808/node-client-api/lib/responder.js:769:33)
    at Operation.responseDispatcher (/Users/rickhedin/work/180808/node-client-api/lib/responder.js:29:29)
    at ClientRequest.callBackMethod (/Users/rickhedin/work/180808/node-client-api/lib/mlutil.js:123:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
Ricks-MBP:node-client-api rickhedin$ 
Ricks-MBP:node-client-api rickhedin$ 
Ricks-MBP:node-client-api rickhedin$ ```

**Comment by rhedin** [comment]
I found this.  https://github.com/marklogic/node-client-api/issues/303   I have Mark Logic server 8 installed.  Maybe it needs to be 9.

**Comment by jmakeig** [comment]
You should definitely be using MarkLogic 9. Please feel free to re-open if you continue to see this issue  after the upgrade.
