### ISSUE TITLE
Fix generated unit tests for MarkLogic Server 9.0 release 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/node-client-api#536]
On internal Jenkins CI env, it is seen that many of generated unit tests for Data Services throw Assert failures such as ones given below. Failures are seen when MarkLogic Server release 9.0 (nightly builds) is used.

Same tests runs fine when MarkLogic Server release 10.0 (nightly builds) is used.

```moduleInitMjs service.initializer endpoint (from Mocha Tests)```
Stacktrace:
```
AssertionError: expected false to deeply equal true
AssertionError: AssertionError: expected false to deeply equal true
    at /space/jenkins/workspace/NodeAPIUnitTests_develop_b9_0/test-basic-proxy/lib/generated/moduleInitMjsTest.js:18:18
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

```postOfMultipartForText service.postOfMultipartForTextDateTime1 endpoint (from Mocha Tests)```
Stacktrace:
```
AssertionError: expected <Buffer 27 75 73 65 20 73 74 72 69 63 74 27 3b 0a 2f 2f 20 64 65 63 6c 61 72 65 55 70 64 61 74 65 28 29 3b 20 2f 2f 20 4e 6f 74 65 3a 20 75 6e 63 6f 6d 6d 65 ... 773 more bytes> to deeply equal '2018-01-02T10:09:08+07:00'
AssertionError: AssertionError: expected <Buffer 27 75 73 65 20 73 74 72 69 63 74 27 3b 0a 2f 2f 20 64 65 63 6c 61 72 65 55 70 64 61 74 65 28 29 3b 20 2f 2f 20 4e 6f 74 65 3a 20 75 6e 63 6f 6d 6d 65 ... 773 more bytes> to deeply equal '2018-01-02T10:09:08+07:00'
    at /space/jenkins/workspace/NodeAPIUnitTests_develop_b9_0/test-basic-proxy/lib/generated/postOfMultipartForTextTest.js:95:18
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by ehennum** [comment]
Here's the root cause:  the tests that are failing use the MarkLogic 10 support for JavaScript Modules.

MarkLogic 9 doesn't support for JavaScript Modules, which is why those tests fail with a 405.

If on MarkLogic 9 we could skip running the tests where the test-basic-proxy/ml-modules/*/* directory contains *.mjs main modules instead of *.sjs or *.xqy main modules, that might be the simplest solution. 

Alternatively, we could keep two versions of those directories:  one with *.mjs main modules for MarkLogic 10 and one with *.sjs main modules for MarkLogic 9.

**Comment by ehennum** [comment]
Following up on the previous comment, @georgeajit , which resolution seems best?

**Comment by georgeajit** [comment]
Tests that rely on ```.mjs``` modules are not run in an environment containing MarkLogic Server build 9.x releases.
