### ISSUE TITLE
Upgrade sampleBy in fromView to throw more predictive error

### ISSUE THREAD

**Issue by anu3990** [marklogic/node-client-api#661]
This issue was reported by @cpisoiu 

The functionality needs to be upgraded to handle the following requests to the server or to throw a predictive error in the bellow cases.

it('sample by limit 2 string', function(done){ 
execPlan( p.fromView('opticUnitTest', 'musician', null, p.fragmentIdCol('musicianDocId')) 
.sampleBy({limit: '2'}))
.then(function (response){ 
     const output = getResults(response); should(output.length).equal(2); done(); })
.catch(done);
});

 
it('sample by limit wrong', function(done){ 
execPlan( p.fromView('opticUnitTest', 'musician', null, p.fragmentIdCol('musicianDocId')) 
.sampleBy({limit:'wrong'}))
.then(function(response){ 
// const output = getResults(response); 
// should(output.length).equal(4); console.log(response); done(); }
)
.catch(done);
});

Currently the error thrown is -
Error: query rows: response with invalid 400 status
    at Operation.makeError (lib/operation.js:226:10)
    at Operation.isResponseStatusOkay (lib/responder.js:968:33)
    at Operation.responseDispatcher (lib/responder.js:46:29)
    at Operation.retryDispatcher (lib/requester.js:271:34)
    at ClientRequest.callBackMethod (lib/mlutil.js:126:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:632:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:501:22)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by anu3990** [comment]
Hi @ehennum and @llinggit any thoughts about this issue?

**Comment by ehennum** [comment]
@anu3990 , the response body for the error may have additional detail that could be provided in the error.

One way to check that approach would be to reproduce the error and log the response body.

If the response body does have useful additional detail, the rows.js library could implement an error transform function that extracts the detail from the response body. The initialization of the Operation object would set the operation.errorTransform property to the error transform function.

The documents.js library has examples of error transform functions.  The implementation of the error transform function is specific to the request and the response body.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
