### ISSUE TITLE
Removing an invalid module will not return an error

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#67]
Try to remove an invalid module

  var dbDir = '/marklogic/query/invalid/custom/';
  var dbModule = 'directoryConstraintInvalid.xqy';
  var dbPath = dbDir + dbModule;
  var fsPath = './test-complete/data/directoryConstraintInvalid.xqy';

  it('should fail to remove the invalid custom query', function(done){
    dbAdmin.config.query.custom.remove(dbModule).
    result(function(response) {
      response.should.equal('SHOULD HAVE FAILED');
      done();
    }, function(error) {
      console.log(error);
      done();
    });
  });

It will return the path instead of an error response

Possibly unhandled AssertionError: expected { path: '/marklogic/query/custom/directoryConstraintInvalid.xqy' } to be 'SHOULD HAVE FAILED'
    at Assertion.fail (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/should/lib/assertion.js:112:17)
    at Assertion.prop.(anonymous function) (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/should/lib/assertion.js:38:14)
    at /space/SVN_HOME/HEAD/qa/node-client-api/test-complete/nodejs-config-query-negative.js:67:23
    at tryCatch1 (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/pr
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/async.js:7
    at Async$consumeFunctionBuffer (/space/SVN_HOME/HEAD/qa/node-client-api/node_modules/bluebird/js/main/async.js:37:14)
    at process._tickCallback (node.js:415:13)

**Comment by ehennum** [comment]
closing because shipped
