### ISSUE TITLE
Cannot find module 'jsdoc/util/doop'

### ISSUE THREAD

**Issue by dberesford** [marklogic/node-client-api#88]
```
$ gulp test

Error: Cannot find module 'jsdoc/util/doop'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dberesford/work/marklogic/node-client-api/node_modules/gulp-jsdoc/node_modules/jsdoc/lib/jsdoc/borrow.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
- same for `gulp doc`
- commenting the jsdoc dependency in the gulp file works around the issue
- I'm on the develop branch, haven't tested this on master

**Comment by iDevPro** [comment]
This issus with gulp-jsdoc, i have projects that use this package and have trouble if package is not installed from npm or npm install another package after this :)
